version: "3.3"

services:
   submodule-updater:
     image: alpine/git:latest
     profiles: ["update"]
     volumes:
       - ./:/repository
     entrypoint: ash /repository/scripts/update_submodule.sh
     environment:
       # Set the raygun4wordpress provider target branch name:
       - PROVIDER_BRANCH=master

   wp-cli:
     depends_on:
       - db
     build:
       dockerfile: Dockerfile
     profiles: ["test"]
     volumes:
       - ./raygun-testing:/test_plugin
       - ./scripts/:/scripts/
     entrypoint: ash /scripts/run_tests.sh
     user: xfs
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_TABLE_PREFIX: "wp_"

   db:
     image: mysql:5.7
     profiles: ["test"]
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

volumes:
    db_data: