version: "3.3"

services:
   runner:
     depends_on:
       db:
         condition: service_healthy
       # Waits for wordpress in run_tests.sh
     image: wordpress:cli
     profiles: ["test"]
     environment:
       - HOME="/tmp"
     env_file:
       - settings.env
     volumes:
       - wp_data:/var/www/html
       - ./scripts:/scripts
       - ./plugins:/plugins
     user: xfs
     entrypoint: bash /scripts/run_tests.sh
     environment:
       # You can enable WordPress debug logging here:
       WORDPRESS_DEBUG_MODE: false
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_TABLE_PREFIX: "wp_"

   wordpress:
     depends_on:
       db:
         condition: service_healthy
     # You can modify the WordPress version here:
     image: wordpress:latest
     profiles: ["test"]
     volumes:
       - wp_data:/var/www/html
     ports:
       - 8000:80
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_TABLE_PREFIX: "wp_"

   db:
     image: mysql:5.7
     profiles: ["test"]
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     healthcheck:
       test: mysqladmin ping -h db --silent --password=wordpress
       interval: 5s
       retries: 4
       timeout: 10s

   submodule-updater:
     image: alpine/git:latest
     profiles: ["update"]
     env_file:
       - settings.env
     volumes:
       - ./:/repository
     entrypoint: ash /repository/scripts/update_submodule.sh

   cleaner:
     image: alpine/git:latest
     profiles: ["clean"]
     env_file:
       - settings.env
     volumes:
       - ./:/repository
     entrypoint: ash /repository/scripts/clean.sh

volumes:
    db_data:
    wp_data: