version: "3.3"

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wp:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     volumes:
       - ./html:/var/www/html
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_TABLE_PREFIX: "wp_"

   # TODO: make this a profile so that the cli is only included if necessary
   wp-cli:
     depends_on:
       - db
       - wp
     image: wordpress:cli
     volumes:
       - ./html:/var/www/html
       - ./scripts/:/scripts/
     entrypoint: bash /scripts/prepare.sh
     user: xfs
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_TABLE_PREFIX: "wp_"
       
    # TODO: make a container with a git image with a profile so that the branch can be changed only if necessary
    #submodule-updater:
      

volumes:
    db_data: