version: "3.3"

services:
   runner:
     depends_on:
       db:
         condition: service_healthy
       wordpress:
         condition: service_healthy
     image: wordpress:cli
     profiles: ["test"]
     env_file:
       - settings.env
     volumes:
       - ./plugins/:/plugins/
       - ./scripts/:/scripts/
     entrypoint: bash /scripts/run_tests.sh

   wordpress:
     depends_on:
       db:
         condition: service_healthy
     image: wordpress:latest
     profiles: ["test"]
     ports:
       - 8000:80
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_TABLE_PREFIX: "wp_"
     healthcheck:
       test: #TODO

   db:
     image: mysql:5.7
     profiles: ["test"]
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     healthcheck:
       test: mysqladmin ping -h db --silent --password=wordpress
       interval: 2s
       retries: 10
       timeout: 5s

   submodule-updater:
     image: alpine/git:latest
     profiles: ["update"]
     env_file:
       - settings.env
     volumes:
       - ./:/repository
     entrypoint: ash /repository/scripts/update_submodule.sh

   cleaner:
     image: alpine/git:latest
     profiles: ["clean"]
     env_file:
       - settings.env
     volumes:
       - ./:/repository
     entrypoint: ash /repository/scripts/clean.sh

volumes:
    db_data: