version: "3.3"

services:
   submodule-updater:
     image: alpine/git:latest
     profiles: ["update_submodule"]
     volumes: 
       - ./:/repository
       - ./scripts/:/scripts/
     entrypoint: ash /scripts/update_submodule.sh
     environment:
       # Set the raygun4wordpress provider target branch name:
       - PROVIDER_BRANCH=master

   db:
     image: mysql:5.7
     profiles: ["testing", "cli_prepare"]
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wp:
     depends_on:
       - db
     image: wordpress:latest
     profiles: ["testing", "cli_prepare"]
     ports:
       - "8000:80"
     volumes:
       - ./html:/var/www/html
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_TABLE_PREFIX: "wp_"

   wp-cli:
     depends_on:
       - db
       - wp
     image: wordpress:cli
     profiles: ["cli_prepare"]
     volumes:
       - ./html:/var/www/html
       - ./scripts/:/scripts/
     entrypoint: bash /scripts/prepare.sh
     user: xfs
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_TABLE_PREFIX: "wp_"

volumes:
    db_data: