version: "3.3"

services:
   runner:
     depends_on:
       - db
     image: wordpress:latest
     profiles: ["test"]
     env_file:
       - settings.env
     volumes:
       - ./plugins/:/plugins/
       - ./scripts/:/scripts/
     entrypoint: bash /scripts/run_tests.sh
     ports:
       - "8000:80"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_TABLE_PREFIX: "wp_"

   db:
     image: mysql:5.7
     profiles: ["test"]
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   submodule-updater:
     image: alpine/git:latest
     profiles: ["update"]
     env_file:
       - settings.env
     volumes:
       - ./:/repository
     entrypoint: ash /repository/scripts/update_submodule.sh

   cleaner:
     image: alpine/git:latest
     profiles: ["clean"]
     env_file:
       - settings.env
     volumes:
       - ./:/repository
     entrypoint: ash /repository/scripts/clean.sh

volumes:
    db_data: